# fly.toml app configuration file generated for haniqa-pos on 2026-02-23T12:07:03+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'haniqa-pos'
primary_region = 'ams'

[build]

[env]
  DATA_DIR = '/data'
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'haniqa_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
